export const SET_INICIO = 'SET_INICIO';
export const SET_TEMPO_GASTO = 'SET_TEMPO_GASTO';
export const SET_VELOCIDADE_MEDIA = 'SET_VELOCIDADE_MEDIA';
export const SET_RENDIMENTO_MEDIO = 'SET_RENDIMENTO_MEDIO';
export const SET_PRECO_COMBUSTIVEL = 'SET_PRECO_COMBUSTIVEL';
